name: Electron Builder CI (WIN)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REF: ${{ github.ref }}
    steps:
    - name: Checkout reposistory
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Checkout drawio-dev
      uses: actions/checkout@v4
      with:
        repository: jgraph/drawio-dev
        token: ${{ secrets.GH_TOKEN }}
        ref: release
        path: drawio-dev
        submodules: false
    - name: Get drawio Tag & Submodules
      run: |
        cd drawio-dev
        # Get the current build tag from draw.io
        $tmp=$Env:GH_REF -replace '/v','/diagramly-' -replace '[.]','_'
        $ref=$tmp+':'+$tmp
        git fetch origin $ref --no-tags
        $tmp=$tmp -replace 'refs/',''
        git checkout $tmp -b tmp-deploy
        Copy-Item -Path "src\main\webapp\js\*.min.js"  -Destination "..\drawio\src\main\webapp\js\"
        cd ..
        Remove-Item 'drawio-dev' -Recurse
    - name: Installing Node
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Prepare for Windows Build
      shell: powershell #The default shell for Windows
      run: |
        npm install -g yarn
        yarn install
    - name: Build for Windows (x64)
      id: win_build
      env:
        CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
        CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
      shell: powershell #The default shell for Windows
      run: |
        #Enable auto-update again
        yarn run sync
        yarn run release-win
        echo "asset_path=dist/*" >> $GITHUB_OUTPUT
    - uses: actions/upload-artifact@v3
      with:
        path: ${{ steps.win_build.outputs.asset_path }}
